[package]
name = "muserial"
version = "0.1.0"
authors = ["Fionn Cleary <fionn.cleary@streamunlimited.com>"]

[dependencies]
chrono = "0.4"
libc = "0.2"
argparse = "0.2"
mio = { version = "0.7", features = ["os-poll", "os-ext"] }
