[package]
name = "muserial"
version = "0.1.0"
authors = ["Fionn Cleary <fionn.cleary@streamunlimited.com>"]
edition = "2018"

[dependencies]
libc = "0.2.74"
argparse = "0.2.2"
io-uring = { version = "0.5.1", features = [] }
chrono = "0.4"
