[package]
name = "muserial"
version = "0.1.0"
authors = ["Fionn Cleary <fionn.cleary@streamunlimited.com>"]
edition = "2021"

[dependencies]
chrono = "0.4"
libc = "0.2"
argparse = "0.2"
smol = "2.0"
futures-lite = "2.0"
async-io = "2.2"
snafu = "0.8"
