[package]
name = "muserial"
version = "0.1.0"
authors = ["Fionn Cleary <fionn.cleary@streamunlimited.com>"]
edition = "2021"

[dependencies]
chrono = "0.4"
libc = "0.2"
argparse = "0.2"
smol = "1.3"
futures-lite = "1.13"
futures-concurrency = "7.4"
